eureka:
  client:
    service-url:
      defaultZone: http://docker.for.mac.host.internal:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
logging:
  level:
    com.insight: info
server:
  compression:
    enabled: true
    mime-types: application/json
  port: 16010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: base-auth
          uri: lb://base-auth
          filters:
            - StripPrefix=0
          predicates:
            - Path=/base/auth/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: docker.for.mac.host.internal
    port: 6379
    password: root
    database: 1
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1